server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        lowerCaseServiceId: true
        enabled: true
      routes:
        - id: diary-service
          uri: lb://BACKEND
          predicates:
            - Path=/api/diary/**
          filters:
            - RewritePath=/api/diary/(?<path>.*), /$\{path}
            - AddAuthInfo
            
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/login
            - Path=/oauth2/**
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
