server:
  port: 8081
  ssl:
    key-store: /etc/letsencrypt/keystore.p12
    key-store-password: sunwoo123
    key-store-type: PKCS12

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8090/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        lowerCaseServiceId: true
        enabled: true
      routes:
        - id: psytest-service
          uri: lb://BACKEND
          predicates:
            - Path=/api/psy/**
          filters:
            - AddAuthInfo
            - RewritePath=^/api/psy/(?<path>.*), /api/v1/$\{path}
            
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/login/**, /oauth2/**

        - id: authentication-resend-token
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/token/resend
          filters:
            - RewritePath=/token/resend/, /account/token/resend

        - id: authentication-account
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/account/**
          filters:
            - AddAuthInfo
            - RewritePath=^/api/account/(?<path>.*), /account/$\{path}

        - id: diary-service
          uri: lb://DIARY-SERVICE
          predicates:
            - Path=/api/diary/**
          filters:
            - AddAuthInfo
            - RewritePath=^/api/diary/(?<path>.*), /api/v1/$\{path}
 
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  roles:
    user:
      paths:
        - /api/psy/**
        - /api/diary/**
    admin:
      paths:
        - /api/admin/**
  pathMatchers:
    permitAll:
      - /login/**
      - /oauth2/**
      - /token/resend/**
      - /actuator/**
   
cors:
  allowed-origins:
    - http://localhost:8100
    - https://localhost
    - http://192.168.0.92:8100
    - http://172.29.11.2:8100
    - http://172.29.8.172:8100
    - http://192.168.219.105:8100
    - http://192.168.219.104:8100
    - capacitor://localhost
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  exposed-headers:
    - Authorization
    - X-Redirect
  max-age: 3600
