server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8090/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        lowerCaseServiceId: true
        enabled: true
      routes:
        - id: diary-service
          uri: lb://BACKEND
          predicates:
            - Path=/api/diary/**
          filters:
            - RewritePath=/api/diary/(?<path>.*), /$\{path}
            - AddAuthInfo
            
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/login/**
            
        - id: authentication-oauth
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/oauth2/**

        - id: pront
          uri: http://front:80
          predicates:
            -Path=/home
          filters:
            - RewritePath=/home/(?<path>.*), /$\{path}
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
