server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: DIARY_SERVICE
          uri: lb://backend
          predicates:
            - Path=/diary/**
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
