jwt:
  secretKey: efwalfjiiljgkneiegojioa8e
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

logging:
  level:
    root: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 659320077987-m8nsjkbks7fq3eb567677k7kjiadmd2c.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope: profile, email

          naver:
            client-id: t1WG_3zkBREXTv4KBkR8
            client-secret: xhCWrTXIS8
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday, birthyear
            client-name: Naver

          kakao:
            client-id: 4e11037af33f52477c955f6b6a4e5524
            client-secret: ojFsaOVsuzG38DVKI2VtG6DWdmFjIvgh
            redirect-uri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, birthday, gender, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

